#     _____  _                       _____                                    _
#    |  __ \| |                     |  __ \                                  | |
#    | |__) | | __ _ _   _  ___ _ __| |__) |_ _ ___ _____      _____  _ __ __| |___
#    |  ___/| |/ _` | | | |/ _ \ '__|  ___/ _` / __/ __\ \ /\ / / _ \| '__/ _` / __|
#    | |    | | (_| | |_| |  __/ |  | |  | (_| \__ \__ \\ V  V / (_) | | | (_| \__ \
#    |_|    |_|\__,_|\__, |\___|_|  |_|   \__,_|___/___/ \_/\_/ \___/|_|  \__,_|___/
#                     __/ |
#                    |___/
#                                Version 1.2


# This is used when an update modifies the config. If checks this value and
#warns you when the config file does not match the version needed. This number
# may be changed when the correct additions to the config are made.
ConfigVersion: 2



# -----------------------------------------
#                 Theme
# -----------------------------------------

# Theme modifies the colors for all text
# used by the plugin that cannot be modified
# under Messages.

# Default: "&6"
color1: "&6"

# Default: "&e"
color2: "&e"

# Default: "&8"
color3: "&8"

# -----------------------------------------
#               Settings
# -----------------------------------------

# This allows players to decide if they want to use a password.
Optional: true

# This modifies the minimum and maximum character length of a password.
MinimumPasswordLength: 1
MaximumPasswordLength: 256

# This sets what happens when the wrong password has been entered.
# Options: kick, tryagain
WrongPassword: "kick"

# Block chat when not logged in.
BlockChat: true

# Block commands when not logged in.
BlockCommands: true

# Block interactions with items and blocks while not logged in.
BlockInteract: true

# Block item drop when not logged in.
BlockItemDrop: true

# Block movement when not logged in.
BlockMovement: true

# -----------------------------------------
#               Messages
# -----------------------------------------

# Login
Login: "&6&lLogin &8» &7You must log in to continue! &e/login [password]"
Register: "&6&lRegister &8» &7You must register to continue! &e/register [password]"
LogInSuccessful: "&6&lLogin &8» &7You have logged in successfully."
LoginUsage: "&6&lLogin &8» &c/login [password]"

# Password
PasswordEnabled: "&6&lPassword &8» &7You have &aenabled &7password protection."
PasswordDisabled: "&6&lPassword &8» &7You have &cdisabled &7password protection."
PasswordSet: "&6&lPassword &8» &7Your password has been set to &e%password%&7."
SetPasswordSuccessful: "&6&lPassword &8» &7You have successfully set your password."
RegisterUsage: "&6&lUsage &8» &7/register [password]"
PasswordIncorrect: "&6&lError &8» &cPassword Is Incorrect. Try again."
PasswordSetUsage: "&6&lUsage &8» &7/password set [password]"

# Errors
AlreadyLoggedIn: "&6&lError &8» &cYou are already logged in!"
AlreadyRegistered: "&6&lError &8» &cYou are already registered!"
NoPermission: "&6&lError &8» &cYou do not have permission to do that."
OutOfBounds: "&6&lError &8» &cPassword must be between 1 and 256 characters long."
MustBeLoggedIn: "&6&lError &8» &cYou must be logged in to do that."
OptionalPasswordsDisabled: "&6&lError &8» &cOptional Passwords are disabled."

# Other
KickMessage: "&cYou entered your password incorrectly."
UpdateAvailable: "&6&lPlayerPasswords &8» &cYou are using an outdated version! Latest version is %version%."
OutdatedConfig: "&6&lPlayerPasswords &8» &cThe config file is outdated. Features using this new file may error if not corrected."